name: Update updates.json

on:
  push:
    branches:
      - main
    paths:
      - '**/*.apk'
  workflow_dispatch:

jobs:
  update-json:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, 'update-json')
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: 🔄 Run update_json.py
        run: |
          python .github/scripts/update_json.py

      - name: 💾 Commit and Push updates.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add updates.json
          git commit -m "CI: auto-update updates.json" || echo "No changes to commit"
          git push
